#!/usr/bin/env bash
# Regenerate src/slate.js — the embedded "OFFLINE" segment.
#
# Edit scripts/slate.py to change what the slate shows, then run this.
# Encoding parameters must stay matched to the live stream (H.264 Main +
# AAC-LC 48kHz stereo) so players can switch from slate to live without
# rebuilding their decoder.
set -euo pipefail

cd "$(dirname "$0")/.."
command -v ffmpeg >/dev/null || { echo "ffmpeg required"; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

python3 scripts/slate.py "$TMP/frames"

# The frame sequence is a ping-pong sweep, so the segment loops seamlessly
# when a player repeats it. -g 30 puts a keyframe on every loop boundary.
ffmpeg -hide_banner -loglevel error -y \
  -framerate 15 -i "$TMP/frames/f%04d.png" \
  -f lavfi -i "anullsrc=channel_layout=stereo:sample_rate=48000" \
  -t 2 \
  -c:v libx264 -preset veryslow -profile:v main -level 3.1 -bf 0 \
  -g 30 -keyint_min 30 -sc_threshold 0 -pix_fmt yuv420p -crf 30 \
  -c:a aac -b:a 16k -ar 48000 -ac 2 \
  -muxdelay 0 -muxpreload 0 -f mpegts "$TMP/offline.ts"

python3 - "$TMP/offline.ts" <<'PY'
import base64, io, sys
ts = open(sys.argv[1], 'rb').read()
b64 = base64.b64encode(ts).decode()
lines = [b64[i:i+96] for i in range(0, len(b64), 96)]
body = "'" + ("' +\n  '".join(lines)) + "'"
out = f'''/**
 * A pre-encoded "OFFLINE" slate segment, served when a stream has no live
 * content.
 *
 * Why a real segment instead of an empty playlist: an empty live playlist
 * makes every player poll indefinitely, and AVPro in particular gives no
 * indication of what is happening. Serving a playable 2s slate means viewers
 * see "OFFLINE / WAITING FOR STREAM" instead of a black void, and -- because
 * the slate never changes -- the playlist and the segment are both cacheable
 * at the edge, so idle viewers stop reaching the Worker at all.
 *
 * Encoded to match the live stream exactly (H.264 Main + AAC-LC 48kHz stereo)
 * so a player can transition from slate to live without rebuilding its
 * decoder.
 *
 * Generated by scripts/make-slate.sh -- do not edit by hand.
 */

const SLATE_B64 =
  {body};

export const SLATE_DURATION = 2.0;

let cached = null;

/** Decode once per isolate; the bytes are immutable. */
export function slateBytes() {{
  if (cached) return cached;
  const bin = atob(SLATE_B64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  cached = buf;
  return cached;
}}
'''
io.open('src/slate.js', 'w', encoding='utf-8').write(out)
print(f"src/slate.js regenerated ({len(ts)} bytes of TS)")
PY
